/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pdcproject2;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author katelyncorreia
 */
public class gameWindow extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(gameWindow.class.getName());
    final int screenWidth = 480;
    final int screenHeight = 480;
    boolean key = false;
    /**
     * Creates new form gameWindow
     */
    public gameWindow() {
        initComponents();
        this.setPreferredSize(new Dimension(screenWidth, screenHeight));
        this.setBackground(Color.DARK_GRAY);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cardPanel = new javax.swing.JPanel();
        initialPanel = new javax.swing.JPanel();
        image1 = new javax.swing.JLabel();
        titleLabel1 = new javax.swing.JLabel();
        titleLabel2 = new javax.swing.JLabel();
        startButton = new javax.swing.JButton();
        highscoresButton = new javax.swing.JButton();
        lastRunButton = new javax.swing.JButton();
        quitButton1 = new pdcproject2.quitButton();
        startPanel = new javax.swing.JPanel();
        image2 = new javax.swing.JLabel();
        titleLabel3 = new javax.swing.JLabel();
        title2Label1 = new javax.swing.JLabel();
        confirmButton1 = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        enterNameBox = new javax.swing.JTextField();
        errorLabel = new javax.swing.JLabel();
        quitButton2 = new pdcproject2.quitButton();
        stage1Panel = new javax.swing.JPanel();
        treeButton = new javax.swing.JButton();
        pathButton = new javax.swing.JButton();
        quitButton3 = new pdcproject2.quitButton();
        welcomeLabel = new javax.swing.JLabel();
        nameDisplayLabel = new javax.swing.JLabel();
        introLabel = new javax.swing.JLabel();
        infoLabel1 = new javax.swing.JLabel();
        image3 = new javax.swing.JLabel();
        treePanel = new javax.swing.JPanel();
        quitButton4 = new pdcproject2.quitButton();
        infoLabel2 = new javax.swing.JLabel();
        image4 = new javax.swing.JLabel();
        takeKeyButton = new javax.swing.JButton();
        goBackTreeButton = new javax.swing.JButton();
        keyLabel = new javax.swing.JLabel();
        hasKeyLabel = new javax.swing.JLabel();
        pathPanel = new javax.swing.JPanel();
        quitButton5 = new pdcproject2.quitButton();
        infoLabel3 = new javax.swing.JLabel();
        image5 = new javax.swing.JLabel();
        unlockFrontDoorButton = new javax.swing.JButton();
        goBackPathButton = new javax.swing.JButton();
        noKeyLabel = new javax.swing.JLabel();
        entrancePanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new java.awt.CardLayout());

        cardPanel.setToolTipText("");
        cardPanel.setMaximumSize(new java.awt.Dimension(480, 480));
        cardPanel.setMinimumSize(new java.awt.Dimension(480, 480));
        cardPanel.setPreferredSize(new java.awt.Dimension(480, 480));
        cardPanel.setLayout(new java.awt.CardLayout());

        initialPanel.setMaximumSize(new java.awt.Dimension(480, 480));
        initialPanel.setMinimumSize(new java.awt.Dimension(480, 480));
        initialPanel.setPreferredSize(new java.awt.Dimension(480, 480));

        image1.setText("jLabel1");

        titleLabel1.setText("Welcome to...");

        titleLabel2.setFont(new java.awt.Font("Kavivanar", 1, 24)); // NOI18N
        titleLabel2.setText("ESCAPE THE MIZTHERY LAIR!!!");

        startButton.setText("Start");
        startButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startButtonActionPerformed(evt);
            }
        });

        highscoresButton.setText("Highscores");

        lastRunButton.setText("Last run");

        javax.swing.GroupLayout initialPanelLayout = new javax.swing.GroupLayout(initialPanel);
        initialPanel.setLayout(initialPanelLayout);
        initialPanelLayout.setHorizontalGroup(
            initialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initialPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(titleLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initialPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(initialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initialPanelLayout.createSequentialGroup()
                        .addComponent(image1)
                        .addGap(218, 218, 218))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, initialPanelLayout.createSequentialGroup()
                        .addComponent(titleLabel2)
                        .addGap(83, 83, 83))))
            .addGroup(initialPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(startButton)
                .addGap(32, 32, 32)
                .addComponent(highscoresButton)
                .addGap(38, 38, 38)
                .addComponent(lastRunButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(quitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        initialPanelLayout.setVerticalGroup(
            initialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(initialPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titleLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(titleLabel2)
                .addGap(130, 130, 130)
                .addComponent(image1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 168, Short.MAX_VALUE)
                .addGroup(initialPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(startButton)
                    .addComponent(highscoresButton)
                    .addComponent(lastRunButton)
                    .addComponent(quitButton1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        cardPanel.add(initialPanel, "initialPanel");

        startPanel.setMaximumSize(new java.awt.Dimension(480, 480));

        image2.setText("image");

        titleLabel3.setText("Welcome to...");

        title2Label1.setFont(new java.awt.Font("Kavivanar", 1, 24)); // NOI18N
        title2Label1.setText("ESCAPE THE MIZTHERY LAIR!!!");

        confirmButton1.setText("Confirm");
        confirmButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButton1ActionPerformed(evt);
            }
        });

        nameLabel.setText("Please enter your name:");

        javax.swing.GroupLayout startPanelLayout = new javax.swing.GroupLayout(startPanel);
        startPanel.setLayout(startPanelLayout);
        startPanelLayout.setHorizontalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(titleLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                                .addComponent(image2)
                                .addGap(218, 218, 218))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                                .addComponent(title2Label1)
                                .addGap(83, 83, 83))))
                    .addGroup(startPanelLayout.createSequentialGroup()
                        .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(errorLabel)
                            .addComponent(nameLabel))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, startPanelLayout.createSequentialGroup()
                        .addComponent(enterNameBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(confirmButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(quitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
        );
        startPanelLayout.setVerticalGroup(
            startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(titleLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(title2Label1)
                .addGap(130, 130, 130)
                .addComponent(image2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 122, Short.MAX_VALUE)
                .addComponent(nameLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(startPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confirmButton1)
                    .addComponent(enterNameBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(quitButton2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addComponent(errorLabel)
                .addGap(33, 33, 33))
        );

        cardPanel.add(startPanel, "startPanel");

        treeButton.setText("Go to the tree");
        treeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                treeButtonActionPerformed(evt);
            }
        });

        pathButton.setText("Follow the path");
        pathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pathButtonActionPerformed(evt);
            }
        });

        welcomeLabel.setText("Welcome to the game");

        introLabel.setText("Find the hidden treasure and survive!");

        infoLabel1.setText("You see a path up ahead and a big tree in the distance.");

        image3.setText("jLabel1");

        javax.swing.GroupLayout stage1PanelLayout = new javax.swing.GroupLayout(stage1Panel);
        stage1Panel.setLayout(stage1PanelLayout);
        stage1PanelLayout.setHorizontalGroup(
            stage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stage1PanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(stage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stage1PanelLayout.createSequentialGroup()
                        .addComponent(treeButton)
                        .addGap(78, 78, 78)
                        .addComponent(pathButton)
                        .addGap(90, 90, 90))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, stage1PanelLayout.createSequentialGroup()
                        .addComponent(image3)
                        .addGap(133, 133, 133)))
                .addComponent(quitButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
            .addGroup(stage1PanelLayout.createSequentialGroup()
                .addGroup(stage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stage1PanelLayout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(introLabel))
                    .addGroup(stage1PanelLayout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addComponent(welcomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nameDisplayLabel))
                    .addGroup(stage1PanelLayout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(infoLabel1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stage1PanelLayout.setVerticalGroup(
            stage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stage1PanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(stage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(welcomeLabel)
                    .addComponent(nameDisplayLabel))
                .addGap(18, 18, 18)
                .addComponent(introLabel)
                .addGap(31, 31, 31)
                .addComponent(infoLabel1)
                .addGap(83, 83, 83)
                .addComponent(image3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 179, Short.MAX_VALUE)
                .addGroup(stage1PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(treeButton)
                    .addComponent(pathButton)
                    .addComponent(quitButton3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );

        cardPanel.add(stage1Panel, "stage1Panel");

        infoLabel2.setText("You walk up to the big tree, investigating it's branches...");

        image4.setText("jLabel1");

        takeKeyButton.setText("Take the key");
        takeKeyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                takeKeyButtonActionPerformed(evt);
            }
        });

        goBackTreeButton.setText("Go back");
        goBackTreeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackTreeButtonActionPerformed(evt);
            }
        });

        keyLabel.setText("You spot a key!!");

        javax.swing.GroupLayout treePanelLayout = new javax.swing.GroupLayout(treePanel);
        treePanel.setLayout(treePanelLayout);
        treePanelLayout.setHorizontalGroup(
            treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, treePanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(image4)
                .addGap(223, 223, 223))
            .addGroup(treePanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(treePanelLayout.createSequentialGroup()
                        .addComponent(hasKeyLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, treePanelLayout.createSequentialGroup()
                        .addGap(0, 56, Short.MAX_VALUE)
                        .addComponent(infoLabel2)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, treePanelLayout.createSequentialGroup()
                        .addGroup(treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(keyLabel)
                            .addGroup(treePanelLayout.createSequentialGroup()
                                .addComponent(takeKeyButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(goBackTreeButton)))
                        .addGap(82, 82, 82)
                        .addComponent(quitButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        treePanelLayout.setVerticalGroup(
            treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treePanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(infoLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(keyLabel)
                .addGap(129, 129, 129)
                .addComponent(image4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 178, Short.MAX_VALUE)
                .addGroup(treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitButton4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBackTreeButton)
                    .addComponent(takeKeyButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hasKeyLabel)
                .addGap(17, 17, 17))
        );

        cardPanel.add(treePanel, "treePanel");

        infoLabel3.setText("You find a big mysterious house with a locked door.");

        image5.setText("jLabel1");

        unlockFrontDoorButton.setText("Unlock the door");
        unlockFrontDoorButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unlockFrontDoorButtonActionPerformed(evt);
            }
        });

        goBackPathButton.setText("Go back");
        goBackPathButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goBackPathButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pathPanelLayout = new javax.swing.GroupLayout(pathPanel);
        pathPanel.setLayout(pathPanelLayout);
        pathPanelLayout.setHorizontalGroup(
            pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pathPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(image5)
                .addGap(223, 223, 223))
            .addGroup(pathPanelLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pathPanelLayout.createSequentialGroup()
                        .addComponent(noKeyLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pathPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(infoLabel3)
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pathPanelLayout.createSequentialGroup()
                        .addComponent(unlockFrontDoorButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                        .addComponent(goBackPathButton)
                        .addGap(82, 82, 82)
                        .addComponent(quitButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        pathPanelLayout.setVerticalGroup(
            pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pathPanelLayout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(infoLabel3)
                .addGap(158, 158, 158)
                .addComponent(image5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                .addGroup(pathPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(quitButton5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goBackPathButton)
                    .addComponent(unlockFrontDoorButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(noKeyLabel)
                .addGap(17, 17, 17))
        );

        cardPanel.add(pathPanel, "pathPanel");

        jLabel1.setText("ENTRANCE");

        javax.swing.GroupLayout entrancePanelLayout = new javax.swing.GroupLayout(entrancePanel);
        entrancePanel.setLayout(entrancePanelLayout);
        entrancePanelLayout.setHorizontalGroup(
            entrancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entrancePanelLayout.createSequentialGroup()
                .addGap(213, 213, 213)
                .addComponent(jLabel1)
                .addContainerGap(211, Short.MAX_VALUE))
        );
        entrancePanelLayout.setVerticalGroup(
            entrancePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(entrancePanelLayout.createSequentialGroup()
                .addGap(117, 117, 117)
                .addComponent(jLabel1)
                .addContainerGap(348, Short.MAX_VALUE))
        );

        cardPanel.add(entrancePanel, "entrancePanel");

        getContentPane().add(cardPanel, "cardPanel");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButton1ActionPerformed
        // take what the player enters as their name
        String name = enterNameBox.getText();
        // error handling if the player does not enter anything as their name
        if(!name.isEmpty()) {
            CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
            cardLayout.show(cardPanel, "stage1Panel");
        } else {
            errorLabel.setText("Please enter your name to start"); // display this on the label below if the player does not enter anything as their name
        }
    }//GEN-LAST:event_confirmButton1ActionPerformed

    private void startButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startButtonActionPerformed
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardLayout.show(cardPanel, "startPanel");
    }//GEN-LAST:event_startButtonActionPerformed

    private void treeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_treeButtonActionPerformed
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardLayout.show(cardPanel, "treePanel");
    }//GEN-LAST:event_treeButtonActionPerformed

    private void pathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pathButtonActionPerformed
        // when the user presses the path button
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardLayout.show(cardPanel, "pathPanel");
    }//GEN-LAST:event_pathButtonActionPerformed

    private void goBackTreeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackTreeButtonActionPerformed
        // user chooses to go back while at tree
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardLayout.show(cardPanel, "stage1Panel");
    }//GEN-LAST:event_goBackTreeButtonActionPerformed

    private void goBackPathButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goBackPathButtonActionPerformed
        // user chooses to go back while on the path
        CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
        cardLayout.show(cardPanel, "stage1Panel");
    }//GEN-LAST:event_goBackPathButtonActionPerformed

    private void takeKeyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_takeKeyButtonActionPerformed
        // taking the key
        // DATABASE FOR ITEMS IS NEEDED HERE if we are doing that
        // for now
        if (key != true) {
            CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
            cardLayout.show(cardPanel, "stage1Panel");
            key = true;
        } else {
            hasKeyLabel.setText("You already have the key!");
        }
    }//GEN-LAST:event_takeKeyButtonActionPerformed

    private void unlockFrontDoorButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unlockFrontDoorButtonActionPerformed
        // if user has key
        if (key != false) {
            CardLayout cardLayout = (CardLayout) cardPanel.getLayout();
            cardLayout.show(cardPanel, "entrancePanel");
        } else {
            noKeyLabel.setText("You need a key!");
        }
    }//GEN-LAST:event_unlockFrontDoorButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new gameWindow().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel cardPanel;
    private javax.swing.JButton confirmButton1;
    private javax.swing.JTextField enterNameBox;
    private javax.swing.JPanel entrancePanel;
    private javax.swing.JLabel errorLabel;
    private javax.swing.JButton goBackPathButton;
    private javax.swing.JButton goBackTreeButton;
    private javax.swing.JLabel hasKeyLabel;
    private javax.swing.JButton highscoresButton;
    private javax.swing.JLabel image1;
    private javax.swing.JLabel image2;
    private javax.swing.JLabel image3;
    private javax.swing.JLabel image4;
    private javax.swing.JLabel image5;
    private javax.swing.JLabel infoLabel1;
    private javax.swing.JLabel infoLabel2;
    private javax.swing.JLabel infoLabel3;
    private javax.swing.JPanel initialPanel;
    private javax.swing.JLabel introLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel keyLabel;
    private javax.swing.JButton lastRunButton;
    private javax.swing.JLabel nameDisplayLabel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JLabel noKeyLabel;
    private javax.swing.JButton pathButton;
    private javax.swing.JPanel pathPanel;
    private pdcproject2.quitButton quitButton1;
    private pdcproject2.quitButton quitButton2;
    private pdcproject2.quitButton quitButton3;
    private pdcproject2.quitButton quitButton4;
    private pdcproject2.quitButton quitButton5;
    private javax.swing.JPanel stage1Panel;
    private javax.swing.JButton startButton;
    private javax.swing.JPanel startPanel;
    private javax.swing.JButton takeKeyButton;
    private javax.swing.JLabel title2Label1;
    private javax.swing.JLabel titleLabel1;
    private javax.swing.JLabel titleLabel2;
    private javax.swing.JLabel titleLabel3;
    private javax.swing.JButton treeButton;
    private javax.swing.JPanel treePanel;
    private javax.swing.JButton unlockFrontDoorButton;
    private javax.swing.JLabel welcomeLabel;
    // End of variables declaration//GEN-END:variables
}
